# 1. Definición del límite
limit_req_zone $remote_addr zone=voting_limit:10m rate=1r/s;

# DNS de Docker (Necesario para usar variables en proxy_pass)
resolver 127.0.0.11 valid=30s;

server {
    listen 80;

    # Headers globales
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";

    # 1. Health Check (Para que Jenkins se ponga VERDE)
    location /health {
        access_log off;
        return 200 'gateway ok';
        add_header Content-Type text/plain;
    }

    # 2. Assets de RESULTADOS (Sin Rate Limit para evitar el 429 al cargar)
    location ~* (angular\.min\.js|app\.js|socket\.io\.js)$ {
        proxy_pass http://result:80;
    }

    # 3. El conflicto del STYLE.CSS (Solución con variables para que Nginx NO CRASHEE)
    location = /style.css {
        set $target_style http://vote:8080;
        if ($http_referer ~* /results/) {
            set $target_style http://result:80;
        }
        proxy_pass $target_style;
    }

    # 4. Assets de VOTACIÓN (Java)
    location ~* ^/(stylesheets|javascripts|images|fonts)/ {
        proxy_pass http://vote:8080;
    }

    # 5. Socket.io
    location /socket.io/ {
        proxy_pass http://result:80/socket.io/;
    }

    # 6. APP DE RESULTADOS (Con Rate Limit y Burst alto para assets)
    location /results/ {
        limit_req zone=voting_limit burst=10 nodelay;
        limit_req_status 429;
        proxy_pass http://result:80/;
    }

    # 7. APP DE VOTACIÓN (Con Rate Limit)
    location / {
        limit_req zone=voting_limit burst=10 nodelay;
        limit_req_status 429;
        proxy_pass http://vote:8080;
    }
}