# Definición de la zona de limitación
# 100r/m es preventivo, burst=20 permite cargar los assets iniciales
limit_req_zone $http_x_forwarded_for zone=voting_limit:10m rate=100r/m;

server {
    listen 80;

    # Importante para que Nginx confíe en los headers del Gateway de Azure
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    # App de Votación
    location / {
        limit_req zone=voting_limit burst=20 nodelay;
        limit_req_status 429;
        
        proxy_pass http://vote:8080;
    }

    # Dashboard de Resultados 
    location /results/ {
        limit_req zone=voting_limit burst=20 nodelay;
        limit_req_status 429;
        
        proxy_pass http://result:80/;
    }

    # Endpoint para que Azure Health Probe sepa que estamos vivos
    location /health {
        access_log off;
        return 200 'gateway ok';
        add_header Content-Type text/plain;
    }
}