# Configuración de limitación de peticiones para evitar abusos
limit_req_zone $binary_remote_addr zone=voting_limit:10m rate=100r/m;

server {
    listen 80;

    # App de Votación
    location / {
        limit_req zone=voting_limit burst=20 nodelay;
        limit_req_status 429;
        proxy_pass http://vote:8080; 
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Dashboard de Resultados
    location /results {
        limit_req zone=voting_limit burst=20 nodelay;
        limit_req_status 429;
        proxy_pass http://result:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Endpoint para que Jenkins verifique si el Gateway está vivo
    location /health {
        return 200 'gateway ok';
        add_header Content-Type text/plain;
    }
}
